stages:
  - deploy
cache:
  paths:
    - node_modules/
deploy:
  image: docker:dind
  stage: deploy
  script:
    - docker build -t app/next .
    - docker run -d -p 3000:3000 --rm --name indipix-ui app/next
  tags:
    - docker
  only:
    - main
