image: node:16

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

Build NodeJS App:
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

Test App:
  stage: Test
  script: yarn lint